repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
        # Ruff version.
      rev: v0.3.2
      hooks:
          # Run the linter.
          - id: ruff
            args: [ --fix ]
          # Run the formatter.
          - id: ruff-format
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
            -   id: check-merge-conflict
            -   id: check-json
            -   id: debug-statements
            -   id: double-quote-string-fixer
            -   id: end-of-file-fixer
            -   id: requirements-txt-fixer
            -   id: trailing-whitespace
