modules:
    -   name: "Dashboards"
        graphql_api: "modules/notebooks/backend/api/lambda/Dockerfile"
            dependencies:
                - Environment
                - Dataset
                - Datasets/list_all_datasets
    -   name: "DataPipelines"
        graphql_api: "modules/datapipelines/backend/api/lambda/Dockerfile"
    -   name: "Datasets"
        graphql_api: "modules/datasets/backend/api/lambda/Dockerfile"
    -   name: "Environments"
        graphql_api: "modules/environments/backend/api/lambda/Dockerfile"
    -   name: "Glossaries"
        graphql_api: "modules/glossaries/backend/api/lambda/Dockerfile"
    -   name: "Groups"
        graphql_api: "modules/groups/backend/api/lambda/Dockerfile"
    -   name: "MlStudio"
        graphql_api: "modules/mlstudio/backend/api/lambda/Dockerfile"
    -   name: "Notebooks"
        graphql_api: "modules/notebooks/backend/api/lambda/Dockerfile"
    -   name: "Organizations"
        graphql_api: "modules/organizations/backend/api/lambda/Dockerfile"
    -   name: "Shares"
        graphql_api: "modules/shares/backend/api/lambda/Dockerfile"
    -   name: "Worksheets"
        graphql_api: "modules/worksheets/backend/api/lambda/Dockerfile"
