modules:
    -   name: "Organizations"
        - path: "modules/organizations"
    -   name: "Environments"
        - path: "modules/environments"
    -   name: "Groups"
        - path: "modules/groups"
    -   name: "Datasets"
        - path: "modules/datasets"
    -   name: "Shares"
        - path: "modules/shares"
    -   name: "Glossaries"
        - path: "modules/glossaries"
    -   name: "Dashboards"
        - path: "modules/dashboards"
    -   name: "Pipelines"
        - path: "modules/datapipelines"
    -   name: "MlStudio"
        - path: "modules/mlstudio"
    -   name: "Notebooks"
        - path: "modules/notebooks"
    -   name: "Worksheets"
        - path: "modules/worksheets"
