name: checkov

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - v2m*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          skip_path: tests/, .github, compose/, docker/dev/
          hard_fail_on: MEDIUM
          soft_fail_on: LOW
          baseline: .checkov.baseline
