name: flake8

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
      - main-v2
      - v2m*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install isort
          python -m pip install flake8
      - name: flake8
        run: python -m flake8 --exclude cdk.out,blueprints --ignore E402,E501,F841,W503,F405,F403,F401,E712,E203 backend/
