name: npm-audit

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - release/*
    - main-v2
    - v2m*

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: |
            ./frontend/package-lock.json
            ./frontend/package.json
      - run: npm ci
        working-directory: frontend
      - run: npm run audit
        working-directory: frontend
